services:
    file-storage-rest-api:
        image: fluxfw/flux-file-storage-rest-api:latest
        ports:
            - [%host_ip%:]9501:9501
        restart: always
        volumes:
            - ./data/file-storage:/file-storage
    other-service:
        depends_on:
            - file-storage-rest-api
        environment:
            [- FLUX_FILE_STORAGE_REST_API_HOST=file-storage-rest-api]
            [- FLUX_FILE_STORAGE_REST_API_PORT=9501]
